export default {
	SESSION_PRIORITY_LOW : 1,
	SESSION_PRIORITY_MEDIUM : 2,
	SESSION_PRIORITY_HIGH : 3,
	SESSION_STATUS_OPEN : 'Open',
	SESSION_STATUS_ASSIGNED : 'Assigned',
	SESSION_STATUS_REASSIGNED : 'Reassigned',
	SESSION_STATUS_END : 'End',
};